service: AdSyncAi

provider:
  name: aws
  stage: dev
  runtime: nodejs20.x
  region: ap-south-1  # Change to your preferred AWS region

functions:
  app:
    handler: dist/app.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

package:
  patterns:
    - dist/**            # Include compiled code
    - node_modules/**    # Include installed dependencies
    - package.json       # Include package metadata
    - package-lock.json  # Ensure correct dependencies
  exclude:
    - "**"